---
- name: Creates EC2 Instance
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Create instance
      ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-0affd4508a5d2481b
        count: 1
        vpc_subnet_id: subnet-02db709af12c127b1
        region: us-east-1
        assign_public_ip: yes