---
- name: Install Wordpress on CentOS 7
  hosts: 54.162.111.45
  become: yes
  become_method: sudo
  tasks: 
    - name: Install httpd package
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - epel-release
        - php
        - wget
        - unzip
        - mariadb-server
        - mysql
      ignore_errors: yes


    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/


    - name: Unzip wordpress
      unarchive:
        src: "/tmp/wordpress-5.4.tar.gz"
        dest: "/var/www/html"
        remote_src: yes


    - name: Move files to html directory
      shell: "sudo mv /var/www/html/wordpress/* /var/www/html"
      ignore_errors: yes


    - name: Move index.html
      shell: "sudo mv /var/www/html/index.html /tmp/"
      ignore_errors: true


    - name: Restart apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
      ignore_errors: yes